server:
  port: 8079
  sprig:
    application:
      name: inatelCrud
    jpa:
      show-sql: false
      hibernate :
        ddl-auto : update
      properties :
        hibernete:
          dialect: org.hibernate.dialect.MySQL7Dialect
  jmx:
    enabled : false
  datasource :
    url : jdbc:mysql://localhost:8081/inatelCurd?allowPublicKeyRetrieval=tue&sslMode=DISABLED
    username: Root2
    password: root 